### ISSUE TITLE
Tags for the weather

### ISSUE THREAD

**Issue by IAmEyad** [JoJo-77/SpotifyWeatherApp#8]
Searching the weather directly in spotify might not return the results we want, we should incorporate some kind of "tag" system that gives different types of weather different keywords so we get more productive results.

**Comment by JoJo-77** [comment]
ill work on a way to sort the tags through the parser and direct the weather to one of the playlists or pair them in some object or json file

**Comment by JoJo-77** [comment]
sorted using a dictionary and tagged under "mood" key
